require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WayPointsController do

  # This should return the minimal set of attributes required to create a valid
  # WayPoint. As you add validations to WayPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "place" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WayPointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all way_points as @way_points" do
      way_point = WayPoint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:way_points).should eq([way_point])
    end
  end

  describe "GET show" do
    it "assigns the requested way_point as @way_point" do
      way_point = WayPoint.create! valid_attributes
      get :show, {:id => way_point.to_param}, valid_session
      assigns(:way_point).should eq(way_point)
    end
  end

  describe "GET new" do
    it "assigns a new way_point as @way_point" do
      get :new, {}, valid_session
      assigns(:way_point).should be_a_new(WayPoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested way_point as @way_point" do
      way_point = WayPoint.create! valid_attributes
      get :edit, {:id => way_point.to_param}, valid_session
      assigns(:way_point).should eq(way_point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WayPoint" do
        expect {
          post :create, {:way_point => valid_attributes}, valid_session
        }.to change(WayPoint, :count).by(1)
      end

      it "assigns a newly created way_point as @way_point" do
        post :create, {:way_point => valid_attributes}, valid_session
        assigns(:way_point).should be_a(WayPoint)
        assigns(:way_point).should be_persisted
      end

      it "redirects to the created way_point" do
        post :create, {:way_point => valid_attributes}, valid_session
        response.should redirect_to(WayPoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved way_point as @way_point" do
        # Trigger the behavior that occurs when invalid params are submitted
        WayPoint.any_instance.stub(:save).and_return(false)
        post :create, {:way_point => { "place" => "invalid value" }}, valid_session
        assigns(:way_point).should be_a_new(WayPoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WayPoint.any_instance.stub(:save).and_return(false)
        post :create, {:way_point => { "place" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested way_point" do
        way_point = WayPoint.create! valid_attributes
        # Assuming there are no other way_points in the database, this
        # specifies that the WayPoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WayPoint.any_instance.should_receive(:update).with({ "place" => "" })
        put :update, {:id => way_point.to_param, :way_point => { "place" => "" }}, valid_session
      end

      it "assigns the requested way_point as @way_point" do
        way_point = WayPoint.create! valid_attributes
        put :update, {:id => way_point.to_param, :way_point => valid_attributes}, valid_session
        assigns(:way_point).should eq(way_point)
      end

      it "redirects to the way_point" do
        way_point = WayPoint.create! valid_attributes
        put :update, {:id => way_point.to_param, :way_point => valid_attributes}, valid_session
        response.should redirect_to(way_point)
      end
    end

    describe "with invalid params" do
      it "assigns the way_point as @way_point" do
        way_point = WayPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WayPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => way_point.to_param, :way_point => { "place" => "invalid value" }}, valid_session
        assigns(:way_point).should eq(way_point)
      end

      it "re-renders the 'edit' template" do
        way_point = WayPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WayPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => way_point.to_param, :way_point => { "place" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested way_point" do
      way_point = WayPoint.create! valid_attributes
      expect {
        delete :destroy, {:id => way_point.to_param}, valid_session
      }.to change(WayPoint, :count).by(-1)
    end

    it "redirects to the way_points list" do
      way_point = WayPoint.create! valid_attributes
      delete :destroy, {:id => way_point.to_param}, valid_session
      response.should redirect_to(way_points_url)
    end
  end

end
